### ISSUE TITLE
Official download and documentation links

### ISSUE THREAD

**Issue by jparreira** [nikapps/ortc-php#1]
Great work guys! But it would be awesome if you could update the download and documentation links:

PHP SDK Download
http://messaging-public.realtime.co/api/download/php/2.1.0/ApiPhp.zip

REST documentation
http://messaging-public.realtime.co/documentation/rest/2.1.0/RestServices.pdf

**Comment by alibo** [comment]
Hi jparreira,
Thank you. I fixed it;)
